version: '3.7'
services:
  nginx:
    image: nginx:latest
    network_mode: "host"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/glare.cs.kent.edu/fullchain.pem:/etc/nginx/key.pem:ro
      - /etc/letsencrypt/live/glare.cs.kent.edu/privkey.pem:/etc/nginx/private.pem:ro
      - /var/www/glare.cs.kent.edu/public_html:/usr/share/nginx/html:ro


networks:
    appwrite:
