version: '3.7'
services:
  frontend:
    image: glare-app
    container_name: glare-app
    volumes:
      - /home/glare/glare-app/config.env:/app/.env
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        REPOSITORY_URL: https://github.com/GLARE-Project/glare-app
        BRANCH_NAME: 43be142de9026b2487b52dd9a8c5ff6f07f88325
        EXPOSED_PORT: 3000
    ports:
      - "3000:3000"
    environment:
      env_file: config.env
    networks:
      - appwrite
    stdin_open: true

networks:
    appwrite:
